apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-frontend
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-fe
  template:
    metadata:
      labels:
        app: lms-fe
    spec:
      containers:
        - name: frontend-container
          image: deekshithdocker/lms-webapp
          imagePullPolicy: Always
          ports:
            - containerPort: 80

