name: backend deployment
on: 
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
jobs:
  deploy:
    runs-on: self-hosted
    steps:   
      - name: checkout the code
        uses: actions/checkout@v4.2.2
      - name: build backend image
        run: |
          cd api
          docker build -t ${{ secrets.DOCKER_USERNAME}}/lms-api:latest .
      - name: docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
      - name: push backend image
        run: |
          docker image tag ${{ secrets.DOCKER_USERNAME}}/lms-api:latest ${{ secrets.DOCKER_USERNAME}}/lms-api:v$GITHUB_RUN_NUMBER
          docker push ${{ secrets.DOCKER_USERNAME}}/lms-api:latest
          docker push ${{ secrets.DOCKER_USERNAME}}/lms-api:v$GITHUB_RUN_NUMBER
          
      - name: Deploy configmaps
        run: |
          kubectl apply -f k8s/be-configmap.yml -n lms
      - name: Deploy backend
        run: |
          kubectl apply -f k8s/be-deployment.yml -n lms
      - name: Deploy clusterIP
        run: |
          kubectl apply -f k8s/be-service.yml -n lms
