name: backend deployment
on: workflow_dispatch
jobs:
  deploy:
    runs-on: self-hosted
    steps:   
      - name: Deploy configmaps
        run: |
          kubectl apply -f k8s/be-configmap.yml -n lms
      - name: Deploy backend
        run: |
          kubectl apply -f k8s/be-deployment.yml -n lms
      - name: Deploy clusterIP
        run: |
          kubectl apply -f k8s/be-service.yml -n lms
