name: database setup
on: workflow_call
jobs:
  database:
    runs-on: self-hosted
    steps:
      - name: create network
        run: |
          if docker network ls --format '{{ .Name }}' | grep -wq lms-network; then
            echo "lms-network exist"
          else
            docker network create lms-network
          fi
      - name: check whether the database lms-db exist or not
        run: |
          if docker ps -a --format '{{ .Names }}' | grep -wq lms-db; then
            echo "lms-db container exists"
          else
            docker container run -dt --name lms-db -p 5432:5432 --network lms-network -e POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD}} postgres
          fi
