name: database deployment
on: workflow_dispatch
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create namespace
        run: |
          kubectl create namespace lms
      - name: Deploy secrets
        run: |
          kubectl apply -f k8s/pg-secret.yml -n lms
      - name: Deploy database
        run: |
          kubectl apply -f k8s/pg-deployment.yml -n lms
      - name: Deploy clusterIP
        run: |
          kubectl apply -f k8s/pg-service.yml -n lms

