name: database deployment
on: workflow_dispatch
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy secrets
        run: |
          kubectl apply -f k8s/pg-secret.yml
      - name: Deploy database
        run: |
          kubectl apply -f k8s/pg-deployment.yml
      - name: Deploy clusterIP
        run: |
          kubectl apply -f k8s/pg-service.yml

