name: database deployment
on: workflow_dispatch
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check if namespace exists
        id: ns-check
        run: |
          if kubectl get namespace lms > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Create namespace if it does not exist
        if: steps.ns-check.outputs.exists == 'false'
        run: kubectl create namespace lms
        
      - name: Deploy secrets
        run: |
          kubectl apply -f k8s/pg-secret.yml -n lms
      - name: Deploy database
        run: |
          kubectl apply -f k8s/pg-deployment.yml -n lms
      - name: Deploy clusterIP
        run: |
          kubectl apply -f k8s/pg-service.yml -n lms

