name: frontend deployment
on: 
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout the code
        uses: actions/checkout@v4.2.2
      - name: build frontend image
        run: |
          cd webapp
          docker build -t ${{ secrets.DOCKER_USERNAME}}/lms-webapp:latest .
      - name: docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
      - name: push frontend image
        run: |
          docker image tag ${{ secrets.DOCKER_USERNAME}}/lms-webapp:latest ${{ secrets.DOCKER_USERNAME}}/lms-webapp:v$GITHUB_RUN_NUMBER
          docker push ${{ secrets.DOCKER_USERNAME}}/lms-webapp:latest
          docker push ${{ secrets.DOCKER_USERNAME}}/lms-webapp:v$GITHUB_RUN_NUMBER
      
      - name: Deploy frontend
        run: |
          kubectl apply -f k8s/fe-deployment.yml -n lms
      - name: Deploy LoadBalancer
        run: |
          kubectl apply -f k8s/fe-service.yml -n lms
