name: lms_k8s
on: 
  workflow_dispatch:

jobs:
  database:
    uses: ./.github/workflows/db_k8_deployment.yml

  backend:
    uses: ./.github/workflows/be_k8_deployment.yml
    needs: database

  frontend:
    uses: ./.github/workflows/fe_k8_deployment.yml
    needs: backend
