name: lms_deployment
on: workflow_dispatch
jobs:
  database:
    uses: ./.github/workflows/db_deployment.yml
  build:
    uses: ./.github/workflows/build_image.yml
    needs: database
  backend:
    uses: ./.github/workflows/be_deployment.yml
    needs: build
  frontend:
    uses: ./.github/workflows/fe_deployment.yml
    needs: build
      

